package cdb

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
)

// NetworkInsert holds the columns set when declaring a network. begin, end and
// broadcast are generated by the database from network and netmask.
type NetworkInsert struct {
	Name            *string
	Network         string
	Netmask         int
	Gateway         *string
	Comment         *string
	Pvid            *int
	Prio            int
	TeamResponsible *string
}

// NetworkIDByName returns the id of the network with this name, if any.
func (oDb *DB) NetworkIDByName(ctx context.Context, name string) (int, bool, error) {
	var id int
	err := oDb.DB.QueryRowContext(ctx, "SELECT id FROM networks WHERE name = ? LIMIT 1", name).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, fmt.Errorf("NetworkIDByName: %w", err)
	}
	return id, true, nil
}

// NetworkIDByAddress returns the id of the network declared with this address and
// netmask, if any.
func (oDb *DB) NetworkIDByAddress(ctx context.Context, network string, netmask int) (int, bool, error) {
	var id int
	err := oDb.DB.QueryRowContext(ctx,
		"SELECT id FROM networks WHERE network = ? AND netmask = ? LIMIT 1", network, netmask).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, false, nil
	}
	if err != nil {
		return 0, false, fmt.Errorf("NetworkIDByAddress: %w", err)
	}
	return id, true, nil
}

// IsAssignableTeam reports whether role names an organisational group: neither a
// privilege group nor a user's private group, as required for team_responsible in
// the historical collector.
func (oDb *DB) IsAssignableTeam(ctx context.Context, role string) (bool, error) {
	var n int
	err := oDb.DB.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM auth_group WHERE role = ? AND privilege = 'F' AND role NOT LIKE 'user\\_%'",
		role).Scan(&n)
	if err != nil {
		return false, fmt.Errorf("IsAssignableTeam: %w", err)
	}
	return n > 0, nil
}

// UserPrimaryGroupRole returns the role of the user's primary group, if any.
func (oDb *DB) UserPrimaryGroupRole(ctx context.Context, userID int64) (string, bool, error) {
	const query = "SELECT auth_group.role FROM auth_group " +
		"JOIN auth_membership ON auth_membership.group_id = auth_group.id " +
		"WHERE auth_membership.user_id = ? AND auth_membership.primary_group = 'T' LIMIT 1"
	var role sql.NullString
	err := oDb.DB.QueryRowContext(ctx, query, userID).Scan(&role)
	return checkRow(err, role.Valid, role.String)
}

// InsertNetwork declares a network and returns its record id.
func (oDb *DB) InsertNetwork(ctx context.Context, n NetworkInsert) (int, error) {
	res, err := oDb.ExecContext(ctx,
		`INSERT INTO networks (name, network, netmask, gateway, comment, pvid, prio, team_responsible)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		n.Name, n.Network, n.Netmask, n.Gateway, n.Comment, n.Pvid, n.Prio, n.TeamResponsible)
	if err != nil {
		return 0, fmt.Errorf("InsertNetwork: %w", err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("InsertNetwork: %w", err)
	}
	oDb.SetChange("networks")
	return int(id), nil
}

// GetNetworkRow returns a declared network, generated columns included.
func (oDb *DB) GetNetworkRow(ctx context.Context, id int) (map[string]any, error) {
	const query = `SELECT id, COALESCE(name, ''), COALESCE(network, ''), netmask,
		COALESCE(broadcast, ''), COALESCE(gateway, ''), COALESCE(begin, ''), COALESCE(end, ''),
		pvid, prio, COALESCE(team_responsible, ''), COALESCE(comment, ''), updated
		FROM networks WHERE id = ?`
	var (
		rowID                                         int
		name, network, broadcast, gateway, begin, end string
		team, comment                                 string
		netmask, pvid                                 sql.NullInt64
		prio                                          int
		updated                                       sql.NullTime
	)
	err := oDb.DB.QueryRowContext(ctx, query, id).Scan(&rowID, &name, &network, &netmask,
		&broadcast, &gateway, &begin, &end, &pvid, &prio, &team, &comment, &updated)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("GetNetworkRow: %w", err)
	}
	row := map[string]any{
		"id": rowID, "name": name, "network": network, "broadcast": broadcast,
		"gateway": gateway, "begin": begin, "end": end, "prio": prio,
		"team_responsible": team, "comment": comment,
	}
	if netmask.Valid {
		row["netmask"] = netmask.Int64
	}
	if pvid.Valid {
		row["pvid"] = pvid.Int64
	}
	if updated.Valid {
		row["updated"] = updated.Time.Format("2006-01-02 15:04:05")
	}
	return row, nil
}
