// Package apifeeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apifeeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /daemon/ping)
	PostFeedDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostFeedDaemonStatus(ctx echo.Context) error

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (POST /instance/action)
	PostFeedInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutFeedInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostFeedInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostFeedInstanceStatus(ctx echo.Context, params PostFeedInstanceStatusParams) error

	// (POST /node/disk)
	PostFeedNodeDisk(ctx echo.Context) error

	// (POST /node/system)
	PostFeedSystem(ctx echo.Context) error

	// (POST /object/config)
	PostFeedObjectConfig(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostFeedDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonPing(ctx)
	return err
}

// PostFeedDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonStatus(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostFeedInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceAction(ctx)
	return err
}

// PutFeedInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutFeedInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutFeedInstanceActionEnd(ctx)
	return err
}

// PostFeedInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceResourceInfo(ctx)
	return err
}

// PostFeedInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFeedInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceStatus(ctx, params)
	return err
}

// PostFeedNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedNodeDisk(ctx)
	return err
}

// PostFeedSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedSystem(ctx)
	return err
}

// PostFeedObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedObjectConfig(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/daemon/ping", wrapper.PostFeedDaemonPing)
	router.POST(baseURL+"/daemon/status", wrapper.PostFeedDaemonStatus)
	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.POST(baseURL+"/instance/action", wrapper.PostFeedInstanceAction)
	router.PUT(baseURL+"/instance/action", wrapper.PutFeedInstanceActionEnd)
	router.POST(baseURL+"/instance/resource_info", wrapper.PostFeedInstanceResourceInfo)
	router.POST(baseURL+"/instance/status", wrapper.PostFeedInstanceStatus)
	router.POST(baseURL+"/node/disk", wrapper.PostFeedNodeDisk)
	router.POST(baseURL+"/node/system", wrapper.PostFeedSystem)
	router.POST(baseURL+"/object/config", wrapper.PostFeedObjectConfig)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuhH+Kxi0D8kMjyRbaTtVn5yLe9x2Ytdy2gfbo4HAFYUTEmAAULGS0X/v4EaR",
	"EijJjpU5M+6TLWK5l28vWCz4HVNRlIID1wqPvuOSSFKABml/Mf7vCuRyvOTU/cQj/MU8wQnmpAA8wsqs",
	"JVjRORTEEOllaZ5PhciBcLxarRIsQZWCK7BM3wwG5g8VXAPX5l9SljmjRDPB+78pwc2zNcM/SpjhEf5D",
	"f61p362q/pUU0xwKJyUFRSUrDRs8wm9Jiq7hSwVK41WC3wxOfobUT5xUei4k+wapEzv8GWLPhZyyNAVu",
	"ZP7p5wB8wTVITnI0BrkAiT5IKaSRfw6QvidQCH7FeHZGKZQa0kepVEpRgtTMRYyY/gZUT74yPReVnlDB",
	"ZywzC22FcqY0EjPkyJEJUIX0nGgk4UvFJCh0dTm+QX1Bh/0ZQNonJes76r5nmmCmoVDbzBtMcRKCXGnJ",
	"eGZs9g+IlGSJV+sH7rUYfKlFCClNdKWQZgUoTYpSoa8sz9EUkISZBDWHFM2ERFyk0AZ3bN/8P7yHwLsL",
	"01WoXlatM+oYbIJE6udbyhGZLWx5DKbtUT/BU8gY3wbBPkZO0joiEOPo+vzdcDj860fChdG8IDqGEpUt",
	"DesSnGDg6bY44OkPCCuJnkeNVaAUE3xSVSyNE1if7Fia5CKLLneyXIBU3j1tG/UckCiBqwVFNGfANUqJ",
	"Jii8sGWY3a1sOKd4dOusTIL314KCDz3oG1b7mPAKO/gDk1xkM5abKPc43G9Fc+Kj0G9fzRRvB2UHHhs2",
	"WKqYlPdMfd5mmsax70C+ECnk0RVfVjrjRELWlVGKfQOz4KNvhBnXw9O1sxjXkIHdbCoFTcUaKwvgqZD7",
	"4bEeairr5XveNaNga2IQisF5wZUmnMI1KFFJChd8JrbhZf5pXS3ay59hqXYvxxOA5BXst9W8HohjJmwW",
	"KnlIfEmLoFX8EJ6dAaFFKXKRLfdL9G6yUO7yxLiuNBshTnSzV12/2KnbsQuM1WgtJmbUR5GCydgd9tRB",
	"s6uls1l/wJ6a4Ev737u6H9jYEcsyChUVReG7kK21VJYTu+vuWlSP20yBL6J0sxweJgV5iFcHt8r4jlVN",
	"ZAY6TlAIzrSQkE6kz/YJFRXvoBaSzkFpSXTc8u4aSb42+rG6HE6XOtomKSpKeBx6j0y6WGBeCaXbPf92",
	"sNR+jfeUNK+UBt+RdTaJTaoDW8VQ2Q+Q3exrn6lRPWLdcICuzdtdO9ou6iqLdE54tpF+UeuFRMyX2ENA",
	"6C63EhZMVGpSlSnRkE6IbsW5efiL6U1jUp7yztHc4et3QHCPN/yheruOgyYs39buDM2rgvBfJJCUTHNA",
	"8FDmhNvjHVIlUDZjFGmB9JwpJCitpAROwYS3nsMdL53E3h2Plo06Htpib+aAfr25uQqnKGry7tXt9fm7",
	"v5wOT+4TNAZ3fPjza5QBB1PfUjRdOplCMnOcUW46YM5bce1QTLlG8dRM5xDDRM2F1MkmNKoqCiKXG8yR",
	"4dtD6EKj8a+Xn/71/o5/vLxBzl9oJkXRVEyLbjUTBA+mH7/jxqSykqVQoAxRLijJ2TfnlVfQy3oJqhTj",
	"mXnVNP8LQP6Ifsc5ZEIzS/s3pABQBNZh783rqMs2g8+FTe3IgFks9kpCP5MMItu5pPE9yGZ6nj8y09x4",
	"MNrbZzs2pt2t156S6GryOmWtSZ6zExxDRC2VjiVjA6mD+qpAf1Br1TCqLbWxAA+kKE3o40Fv0DvZGwbd",
	"JceeymklmV6OjbZO1JQoRs8q13pYK+zUwDxdy5prXbqRBZEgA7X7dR4i4R//vQkzYMvCrm7yWK2S+vDj",
	"cxqHkjsDSEEiUrKGA0f4tDfoDewmXgI3iyM8tI9cy2St6LtJT78MfYdQertaXLvBT73Zd03fbLYZf9jM",
	"vEjxKNbeONxB6bciXT7frHVb0KrtYy0r2Bynnw5OuxjXdP2OkewqwaeDN9toFUzZutVGKYzMEj/n88D7",
	"VaZQrWgz4PDothVqt/er5HsrnG7vVyZkSaZMFJPMAHlvWLQlPNG5ez06DkXz+D71op7fqxuzYHvxMNjP",
	"wBCt70b20Z40LjT20Q4bFxG7aQ3Rs8WLoKpf14rv2B/f2t7/O+jxV5JltkJtgP64i5O9Q+jLf/5u4A1w",
	"ldU0Z9TjFZr4/nq6Hc+wt24yXQ+nTSkgKGML4OHcZAryjlwLI5mzMEk9RrZ55ofn1zNK3RzWRsLBgxfG",
	"/C84WRNcVpEw+8DTpwVZFYmxD3bo/rsIs2gYuOuXF16x6wpUj9FCixgvRJ/soR8JiagE819ggAIDZBgc",
	"UIhaU/rjxElU1FOjJm6oacBNMG1dcD6/h/Z1YWMt5HqIcto7WfvGt4gp0aR3gGvqjqz5NcptHOs1Sb/5",
	"tYqx5pgufUwnN9jhTI+MsrNkpCpKQalZledL9EotOZ1LwUWlXrtW/XQ/p/UNd6gt6BXZ5PQiS405uvTT",
	"cOV5WHWxk2bzjkJuDF+5sN0RxOGa5kg1ZX0L9NRC0mXTEWuIhb4xZ4mCbwBEjsioR8UC5HIH0GPH7zgw",
	"e2WfinEwg2iy53ueF5mK7Y+CDk9H3wUemoqt+8vjxElLxA9v7T8rHxtDRn9EbiskQVeSI1KyxgXI1in6",
	"P/XSD52id8EbpHeerZ90BqakJFOWMztzvV85VOUitBmVzPEItz5jw6v71f8CAAD//wBaVLIrKwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
