// Package apifeeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apifeeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (POST /feed/daemon/ping)
	PostFeedDaemonPing(ctx echo.Context) error

	// (POST /feed/daemon/status)
	PostFeedDaemonStatus(ctx echo.Context) error

	// (POST /feed/instance/action)
	PostFeedInstanceAction(ctx echo.Context) error

	// (PUT /feed/instance/action)
	PutFeedInstanceActionEnd(ctx echo.Context) error

	// (POST /feed/instance/resource_info)
	PostFeedInstanceResourceInfo(ctx echo.Context) error

	// (POST /feed/instance/status)
	PostFeedInstanceStatus(ctx echo.Context, params PostFeedInstanceStatusParams) error

	// (POST /feed/node/disk)
	PostFeedNodeDisk(ctx echo.Context) error

	// (POST /feed/node/system)
	PostFeedSystem(ctx echo.Context) error

	// (POST /feed/object/config)
	PostFeedObjectConfig(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostFeedDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonPing(ctx)
	return err
}

// PostFeedDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonStatus(ctx)
	return err
}

// PostFeedInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceAction(ctx)
	return err
}

// PutFeedInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutFeedInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutFeedInstanceActionEnd(ctx)
	return err
}

// PostFeedInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceResourceInfo(ctx)
	return err
}

// PostFeedInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFeedInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceStatus(ctx, params)
	return err
}

// PostFeedNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedNodeDisk(ctx)
	return err
}

// PostFeedSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedSystem(ctx)
	return err
}

// PostFeedObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedObjectConfig(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.POST(baseURL+"/feed/daemon/ping", wrapper.PostFeedDaemonPing)
	router.POST(baseURL+"/feed/daemon/status", wrapper.PostFeedDaemonStatus)
	router.POST(baseURL+"/feed/instance/action", wrapper.PostFeedInstanceAction)
	router.PUT(baseURL+"/feed/instance/action", wrapper.PutFeedInstanceActionEnd)
	router.POST(baseURL+"/feed/instance/resource_info", wrapper.PostFeedInstanceResourceInfo)
	router.POST(baseURL+"/feed/instance/status", wrapper.PostFeedInstanceStatus)
	router.POST(baseURL+"/feed/node/disk", wrapper.PostFeedNodeDisk)
	router.POST(baseURL+"/feed/node/system", wrapper.PostFeedSystem)
	router.POST(baseURL+"/feed/object/config", wrapper.PostFeedObjectConfig)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuhH+Kxi0D8kMjyRbaTtVn5yLe9x2Ytdy2gfbo4HAFYUTEmAAULGS0X8/gwtv",
	"IijJjpU5M8mTLQLcy7ffLpZLfsVUZLngwLXCk684J5JkoEHaX4z/twC5nq45dT/xBH8yV3CEOckAT7Ay",
	"axFWdAkZMZv0OjfX50KkQDjebDYRlqBywRVYoa9GI/OHCq6Ba/MvyfOUUaKZ4MPflODmWi3wzxIWeIL/",
	"NKwtHbpVNbySYp5C5rTEoKhkuRGDJ/g1idE1fCpAabyJ8KvRyffQ+oGTQi+FZF8gdmrH30PtuZBzFsfA",
	"jc6/fB+AL7gGyUmKpiBXINE7KYU0+s8B4rcEMsGvGE/OKIVcQ/wok3IpcpCaOcaI+W9A9ewz00tR6BkV",
	"fMESs9A2KGVKI7FAbjsyBFVIL4lGEj4VTIJCV5fTGzQUdDxcAMRDt3PoBUaYachUV3BDII5KgistGU+M",
	"v/4CkZKs8aa+4G4LQRdbdJDSRBcKaZaB0iTLFfrM0hTNAUlYSFBLiNFCSMRFDG1gp/bOn9Dug3YXnpuy",
	"almzzqgTsA0Qqa53jCMyWdmyWLq2x/wIzyFhvAuCvYycppoNiHF0ff5mPB7//T3hwlieER1CicqWhVXp",
	"jTDwuKsOePwNynKil0FnFSjFBJ8VBYvDG2xMdizNUpEEl3tFrkAqH562j3oJSOTA1YoimjLgGsVEE1Te",
	"0HHMnlKWyjGe3DovozL6taIyhh70La89J7zBDv5SSCqSBUsNyz0O9x02R56F/thqpneblD14bPlgd4W0",
	"vGXqY1doHMa+B/lMxJAGV3xJ6eWJhKQvoxT7AmbBs2+CGdfj0zpYjGtIwB4yhYKmYY2VFfBYyP3w2Ag1",
	"jfX6vexKUOlrZBAKwXnBlSacwjUoUUgKF3whuvAyf7WqFu3lj7BWu5fDCUDSAvb7am4vN4dc2C5U8hB+",
	"SYugNfwQmb2E0CIXqUjW+zX6MFkod0ViWlWaLYoT3exR6xt7bTt2gbEW1WpCTr0XMZiM3eFPRZpdrZzN",
	"+gPO1Ahf2v/eVL3A1omY50GoqMgy34F01mKZz+ypu2tRPe4wBb4K7luk8DDLyEO4OrhVxnesaiIT0OEN",
	"meBMCwnxTPpsn1FR8J7dQtIlKC2JDnveXyPJ50YvVpXD+VoH2yRFRQ6PQ++RSRci5pVQut3rd8lSxTXc",
	"T9K0UBp8R9bbJDZ3HdgqlpX9AN3NnvaZGtUj1g0HaO3e7trRDlFfWaRLwpOt9At6LyRivsQeAkJ/uZWw",
	"YqJQsyKPiYZ4RnSL5+biL6Y3DWl5yj1HC4ev3yWCe6LhH6a7dRw0YWnXujO0LDLCf5FAYjJPAcFDnhJu",
	"H+2QyoGyBaNIC6SXTCFBaSElcAqG3noJdzx3Ggd3PFg2Kj601d4sAf16c3NVPkVRk3cvbq/P3/ztdHxy",
	"H6EpuMeHv75ECXAw9S1G87XTKSQzjzPKTQXM81bYOhQyrlE8NdMphDBRSyF1tA2NKrKMyPWWcGTkDhC6",
	"0Gj66+WH/7y94+8vb5CLF1pIkTUN06LfzAjBg+nH77hxKS9kLhQosykVlKTsi4vKCxgkgwgVivHE3Gqa",
	"/xUg/3h+xzkkQjO79x9IAaAArOPBq5fBkG2Tz9GmCmSJWYh7OaEfSQKB41zS8BlkMz1NH5lpbiwY7O2T",
	"HQfT7tZrT0l0NblOWeuSl+wUhxBRa6VDydhA6qC+qtx/UGvVcKqttbEADyTLDfXxaDAanOylQX/JsU/l",
	"tJBMr6fGWqdqThSjZ4VrPawXdmpgrta6llrnbmRBJMhyt/t1XjLhX/+/KWe/VoRd3Zax2UTVw4/PaVyW",
	"3AVADBKRnDUCOMEnxu8Te4rnwM3qBI8Ho8EIu57JujGMBVXDasNX7Js2g6rNr4sYT/A/QU8/kySxdrXm",
	"0KePHJPuHT1d/rsxaA4xplI/NJvq6fC+vePGVHf3XrPJ8o4kyvZuxTxlFN+ba24u5+Zjw7zs1oTS3Rp7",
	"7cZlVYvUN6+0NaqNd6ApdGwFpV+LeP18k+muok07M7QsYNMJ+ul+FHsG2JsIn45eddHKmLLVvo1SOWiM",
	"/GTUA+9XmUKVoc00xZPbVoLe3m+ir60kvL3f3NcBJokBshvf+mh/QoT3hnVanjfHD6xX9fyh3Rqh22wc",
	"HZKNoz9Mlj8bacqmflhPu8O0ee0m1dWw2pCcoIStgJfPUaY+7yBQOaI5Kyerx6CQF344aZ5R6/bwNnBQ",
	"ePDKsf8PzMAI50WAZu94/DSSFQGOvbND+D8EzYI0cK9jfpahRhmqZmtl3xiuRh/sJAAJiagE818pAJUC",
	"kBFwQDVqje6PQ5agqqdSJ+yo6coNozpvPY8Upn1NxlQLWY9XTgcndYB8GxQTTQYHxKdqOJrfp9yGAa+3",
	"DJvfrxiXjhnXxzQqox0R9cgoO2VGqqAUlFoUabpGL9Sa06UUXBTqpWtHT/dLqt99l1UGvSDbkn7comN6",
	"9GFcvhE9rM7YQbS5RyE3pS8cd3cwuXyLc6TqUr8kempJ6fPp2NXE4t+YxQQjYFBEbpOxkYoVyPUOtKdO",
	"3nGw9sY+FejSDaLJnu99ftykbH89dHhi+vbw0KRsveg8DllaKr75uP9emdmYRvqpWtsgCbqQHJGcNd6U",
	"dAZv/6uWvmnwtgveUnvvOO5JYzNKcjJnKbPD2fuNQ1Wuyq6jkCme4PpbN5IzvLnf/B4AAP//w3aXdUwr",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
