// Package apifeeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package apifeeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (POST /feed/daemon/ping)
	PostFeedDaemonPing(ctx echo.Context) error

	// (POST /feed/daemon/status)
	PostFeedDaemonStatus(ctx echo.Context) error

	// (POST /feed/instance/action)
	PostFeedInstanceAction(ctx echo.Context) error

	// (PUT /feed/instance/action)
	PutFeedInstanceActionEnd(ctx echo.Context) error

	// (POST /feed/instance/resource_info)
	PostFeedInstanceResourceInfo(ctx echo.Context) error

	// (POST /feed/instance/status)
	PostFeedInstanceStatus(ctx echo.Context, params PostFeedInstanceStatusParams) error

	// (POST /feed/node/disk)
	PostFeedNodeDisk(ctx echo.Context) error

	// (POST /feed/node/system)
	PostFeedSystem(ctx echo.Context) error

	// (POST /feed/object/config)
	PostFeedObjectConfig(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostFeedDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonPing(ctx)
	return err
}

// PostFeedDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedDaemonStatus(ctx)
	return err
}

// PostFeedInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceAction(ctx)
	return err
}

// PutFeedInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutFeedInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutFeedInstanceActionEnd(ctx)
	return err
}

// PostFeedInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceResourceInfo(ctx)
	return err
}

// PostFeedInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFeedInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedInstanceStatus(ctx, params)
	return err
}

// PostFeedNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedNodeDisk(ctx)
	return err
}

// PostFeedSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedSystem(ctx)
	return err
}

// PostFeedObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostFeedObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFeedObjectConfig(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.POST(baseURL+"/feed/daemon/ping", wrapper.PostFeedDaemonPing)
	router.POST(baseURL+"/feed/daemon/status", wrapper.PostFeedDaemonStatus)
	router.POST(baseURL+"/feed/instance/action", wrapper.PostFeedInstanceAction)
	router.PUT(baseURL+"/feed/instance/action", wrapper.PutFeedInstanceActionEnd)
	router.POST(baseURL+"/feed/instance/resource_info", wrapper.PostFeedInstanceResourceInfo)
	router.POST(baseURL+"/feed/instance/status", wrapper.PostFeedInstanceStatus)
	router.POST(baseURL+"/feed/node/disk", wrapper.PostFeedNodeDisk)
	router.POST(baseURL+"/feed/node/system", wrapper.PostFeedSystem)
	router.POST(baseURL+"/feed/object/config", wrapper.PostFeedObjectConfig)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuhH+Kxi0D8kMjyRbaTtVn5yLe9x2Ytdy2gfbo4HAFYUTEmAAULGS0X8/gwtv",
	"IijJjpU5M8lTYgDcy7ffLpZLfcVUZLngwLXCk684J5JkoEHavxj/bwFyPV1z6v7EE/zJrOAIc5IBnmBl",
	"9iKs6BIyYg7pdW7W50KkQDjebDYRlqBywRVYoa9GI/MPFVwD1+a/JM9TRolmgg9/U4KbtVrgnyUs8AT/",
	"aVhbOnS7anglxTyFzGmJQVHJciMGT/BrEqNr+FSA0ngT4Vejk++h9QMnhV4Kyb5A7NSOv4facyHnLI6B",
	"G51/+T4AX3ANkpMUTUGuQKJ3Ugpp9J8DxG8JZIJfMZ6cUQq5hvhRJuVS5CA1c4wR89+A6tlnppei0DMq",
	"+IIlZqNtUMqURmKB3HFkCKqQXhKNJHwqmASFri6nN2go6Hi4AIiH7uTQC4ww05CpruCGQByVBFdaMp4Y",
	"f/0CkZKs8aZecI+FoIstOkhpoguFNMtAaZLlCn1maYrmgCQsJKglxGghJOIihjawU/vkT2j3QbsLz01Z",
	"taxZZ9QJ2AaIVOsd44hMVrYslq7tMT/Cc0gY74Jgl5HTVLMBMY6uz9+Mx+O/vydcGMszokMoUdmysCq9",
	"EQYed9UBj79BWU70MuisAqWY4LOiYHH4gI3Jjq1ZKpLgdq/IFUjlw9P2US8BiRy4WlFEUwZco5hogsoH",
	"Oo7ZW8pSOcaTW+dlVEa/VlTG0IO+5bXnhDfYwV8KSUWyYKlhucfhvsPmyLPQX1vN9G6TsgePLR/sqZCW",
	"t0x97AqNw9j3IJ+JGNLgji8pvTyRkPRllGJfwGx49k0w43p8WgeLcQ0J2EumUNA0rLGzAh4LuR8eG6Gm",
	"sV6/l10JKn2NDEIhOC+40oRTuAYlCknhgi9EF17mV6tq0d7+CGu1ezucACQtYL+v5vHycMiF7UIlD+GX",
	"tAhaww+R2UsILXKRimS9X6MPk4VyVySmVaXZojjRzR61frDXtmMXGGtRrSbk1HsRg8nYHf5UpNnVytms",
	"P+BOjfCl/d+bqhfYuhHzPAgVFVnmO5DOXizzmb11d22qx12mwFfBc4sUHmYZeQhXB7fL+I5dTWQCOnwg",
	"E5xpISGeSZ/tMyoK3nNaSLoEpSXRYc/7ayT53OjFqnI4X+tgm6SoyOFx6D0y6ULEvBJKt3v9LlmquIb7",
	"SZoWSoPvyHqbxOapA1vFsrIfoLvZ0z5To3rEuuEArd3bXTvaIeori3RJeLKVfkHvhUTMl9hDQOgvtxJW",
	"TBRqVuQx0RDPiG7x3Cz+YnrTkJanPHO0cPj6XSK4Jxr+Zbpbx0ETlnatO0PLIiP8FwkkJvMUEDzkKeH2",
	"1Q6pHChbMIq0QHrJFBKUFlICp2DorZdwx3OncXDHg2Wj4kNb7c0S0K83N1flWxQ1effi9vr8zd9Oxyf3",
	"EZqCe33460uUAAdT32I0XzudQjLzOqPcVMC8b4WtQyHjGsVTM51CCBO1FFJH29CoIsuIXG8JR0buAKEL",
	"jaa/Xn74z9s7/v7yBrl4oYUUWdMwLfrNjBA8mH78jhuX8kLmQoEyh1JBScq+uKi8gEEyiFChGE/Mo6b5",
	"XwHyr+d3nEMiNLNn/4EUAArAOh68ehkM2Tb5HG2qQJaYhbiXE/qRJBC4ziUN30E209P0kZnmxoLB3j7Z",
	"cTHtbr32lERXk+uUtS55yU5xCBG1VjqUjA2kDuqryvMHtVYNp9paGxvwQLLcUB+PBqPByV4a9Jcc+1ZO",
	"C8n0emqsdarmRDF6VrjWw3phpwZmtda11Dp3IwsiQZan3V/nJRP+9f+bcvZrRdjdbRmbTVS9/PicxmXJ",
	"XQDEIBHJWSOAE3xi/D6xt3gO3OxO8HgwGoyw65msG8NYUDWsDnzFvmkzqNr8uojxBP8T9PQzSRJrV2sO",
	"ffrIMene0dPlvxuD5hBjKvVDc6ieDu87O25MdXefNYcs70iibO9WzFNG8b1Zc3M5Nx8b5mW3JpTu1thr",
	"Ny6rWqS+eaWtUW28A02hYyso/VrE6+ebTHcVbdqZoWUBm07QT/ej2DPA3kT4dPSqi1bGlK32bZTKQWPk",
	"J6MeeL/LFKoMbaYpnty2EvT2fhN9bSXh7f3mvg4wSQyQ3fjWV/sTIrw3rNPyvjl+YL2q5w/t1gjdZuPo",
	"kGwc/WGy/NlIUzb1w3raHabNazeprobVhuQEJWwFvHyPMvV5B4HKEc1ZOVk9BoW88MNJ84xat4e3gYvC",
	"g1eO/X9gBkY4LwI0e8fjp5GsCHDsnR3C/yFoFqSB+xzzsww1ylA1Wyv7xnA1+mAnAUhIRCWY/5UCUCkA",
	"GQEHVKPW6P44ZAmqeip1wo6artwwqvPV80hh2tdkTLWQ9XjldHBSB8i3QTHRZHBAfKqGo/n7lNsw4PWR",
	"YfP3K8alY8b1MY3KaEdEPTLKTpmRKigFpRZFmq7RC7XmdCkFF4V66drR0/2S6m/fZZVBL8i2pB+36Jge",
	"fRiXX0QPqzN2EG2eUchN6QvH3R1MLr/iHKm61B+JnlpS+nw6djWx+DdmMcEIGBSRO2RspGIFcr0D7amT",
	"dxysvbFPBbp0g2iy5/c+P25Stn89dHhi+vbw0KRsfeg8DllaKr75uv9emdmYRvqpWtsgCbqQHJGcNb6U",
	"dAZv/6u2vmnwtgveUnvvOO5JYzNKcjJnKbPD2fuNQ1Wuyq6jkCme4KGgY7y53/weAAD//wSPW5BDKwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
