// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/node)
	PostAuthNode(ctx echo.Context) error

	// (GET /nodes/{node_id}/compliance/candidate_modulesets)
	GetNodeComplianceCandidateModulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/candidate_rulesets)
	GetNodeComplianceCandidateRulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/logs)
	GetNodeComplianceLogs(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/modulesets)
	GetNodeComplianceModulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (DELETE /nodes/{node_id}/compliance/modulesets/{mset_id})
	DeleteNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (POST /nodes/{node_id}/compliance/modulesets/{mset_id})
	PostNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (GET /nodes/{node_id}/compliance/rulesets)
	GetNodeComplianceRulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (DELETE /nodes/{node_id}/compliance/rulesets/{rset_id})
	DeleteNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (POST /nodes/{node_id}/compliance/rulesets/{rset_id})
	PostNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /tags)
	GetTags(ctx echo.Context) error

	// (GET /tags/{tag_id})
	GetTag(ctx echo.Context, tagId int) error

	// (GET /tags/{tag_id}/nodes)
	GetTagNodes(ctx echo.Context, tagId int) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAuthNode converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthNode(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthNode(ctx)
	return err
}

// GetNodeComplianceCandidateModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateModulesets(ctx, nodeId)
	return err
}

// GetNodeComplianceCandidateRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateRulesets(ctx, nodeId)
	return err
}

// GetNodeComplianceLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceLogs(ctx, nodeId)
	return err
}

// GetNodeComplianceModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceModulesets(ctx, nodeId)
	return err
}

// DeleteNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// PostNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// GetNodeComplianceRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceRulesets(ctx, nodeId)
	return err
}

// DeleteNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// PostNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetTags converts echo context to params.
func (w *ServerInterfaceWrapper) GetTags(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTags(ctx)
	return err
}

// GetTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTag(ctx, tagId)
	return err
}

// GetTagNodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetTagNodes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTagNodes(ctx, tagId)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/node", wrapper.PostAuthNode)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_modulesets", wrapper.GetNodeComplianceCandidateModulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_rulesets", wrapper.GetNodeComplianceCandidateRulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/logs", wrapper.GetNodeComplianceLogs)
	router.GET(baseURL+"/nodes/:node_id/compliance/modulesets", wrapper.GetNodeComplianceModulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.DeleteNodeComplianceModuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.PostNodeComplianceModuleset)
	router.GET(baseURL+"/nodes/:node_id/compliance/rulesets", wrapper.GetNodeComplianceRulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.DeleteNodeComplianceRuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.PostNodeComplianceRuleset)
	router.GET(baseURL+"/openapi.json", wrapper.GetSwagger)
	router.GET(baseURL+"/tags", wrapper.GetTags)
	router.GET(baseURL+"/tags/:tag_id", wrapper.GetTag)
	router.GET(baseURL+"/tags/:tag_id/nodes", wrapper.GetTagNodes)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW3PbNhP9Kxh83yMryon7EL05dpNJm7gZJW0fHE8GAlcSMhTALJaJVQ3/ewcAb7Ko",
	"m9WRY02fbJFL7OUc7FmQCy7NLDMaNFk+WPBMoJgBAfpfSr8XNH1ngd4k7ncCVqLKSBnNB/zNFTNjRlNg",
	"M5PkKVggHnHlbmWCpjziWsyAD/jMAn1WCY84wtdcISR8QJhDxK2cwky4pWmeOVNLqPSEF0VUOr82CWx2",
	"rk0C3X7dnYf6HW5NGjeljA9IuXDGNjPagq/+eb/v/kijCTS5f0WWpUoKF0r8xbp4Fq31/o8w5gP+v7iB",
	"NA53bfwezSiFWfCynNFLkbAhfM3BEi8ift4/O4bXP7TIaWpQ/Q1JcPv8GG5fGRypJAEdfJ4fw+e1IfbK",
	"5LrM88UxfF4aPU6V9Ij+fBwevdEEqEXKPgB+A2S/IBr0O6p82K1dPe9aDZoMkFQgO8Edre62CzbNZ0L/",
	"hCASMUqBwV2WCu0jZzYDqcZKMjKMpsoyI2WOCFpCuUc/6Sz4633SPOrY683mvAkR3NZWZvQFQv2+AVoV",
	"irQcc+sG3IlZlrrn+r1+72yrs+rRVX+uXiBzVDT/4OoWXI2EVfIip2kNlXvGX218TYkyF/AIBAJW1uHX",
	"K4MzQXzAf/3rI49aS/i799cIfXBsPDKKfGImA22/SSZNmoIkg0xkirfKw896/d4zF4AzdTcH/Hmv3+vz",
	"yHdHn0jstn3se7arp7EdqA9hoiwBMuGbO3OPgKaSsR5KB4P/5Xo0f28suXSvgxRg6GYvTTLfi/jL6Ios",
	"6+jSkVeV0OUXW0CuLTtQXun2z/bcpcvB1mDdjzbPVbI9Um9VQt4V7P29fiElZLTUubu6Rp1g7Iya7rfN",
	"9kWrbW22dUbtLcMHN0ub5ea2iBZLG+LmtnAZiol1iTtq8Vu3guekjRfl0FB4f6kSWkIshU5UIgg+15OO",
	"r/oEOtj7GojVDzSjkWVjUzG6g8KvgRx7L2unl9US7xqX0dJ8dtNdnMYkXhqhXNoHMU4RzGyLS02HLC8I",
	"RDHvostbZcm15K6ytIT4vmwmbrgjNq60s2TEGtmxQXagkZ0HcqJucPsQA/ejBR5IiuHpUQJPgRCpmWyh",
	"QG3LnO2e+L91yz9VyC87Uq8PcE8Z9B1FoSUFgkjIKSRudN0d/RNSgroAJyIETRrxonzdUYQQUyBYDfYK",
	"XP5MNPmzMZrZejJc+YXW8OFAOkQ72pcvgjro04FaHRyzuZRg7ThP0zlLIAC/GW2DrcI8NvTRmmPKBa1g",
	"uGk7u0PKD4Tfw45IHSeD5Rdcq8eaZ5u4UfWBQIf+LoeDfust1Tbbs30PKEc5dOzRV3YaK/EwWRmenKic",
	"xCiJtaDgPoKCD5aT4VGb0XAfMRkeJCX4VIQEHyQjj4jbY4rI8D8JafpI+ca1VxW71IqVzv/hu5hM/Pve",
	"g3r11heEv//2w5S4KlmWj1Ily3qFi2s01esJ3ClLSk+YN+0Q0Y/h+iNpXijwo3DNXY8XJCaVJnUW8UrZ",
	"LBVzVz5Wvquerynjauda982VvHHH99YQzS6fW5UmcDugOHhg2XkTnO9C7PMfA88wkWwcN70F+z4FhAoU",
	"pprhcw3I137dp4n04aNpWTNF0/Cp0qW3bmz5KCado8pxWdH6uNnJBATKUTORKVaZdgD/Z33rIAA2fZKu",
	"vP87TbIuh8jESKXKf2C7LUJl3UwYaJtjyge8F/PitvgnAAD///FYcGZEIwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
