// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /docs/openapi)
	GetSwagger(ctx echo.Context) error

	// (GET /nodes/{node_id}/compliance/candidate_modulesets)
	GetNodeComplianceCandidateModulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/candidate_rulesets)
	GetNodeComplianceCandidateRulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/logs)
	GetNodeComplianceLogs(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/modulesets)
	GetNodeComplianceModulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (DELETE /nodes/{node_id}/compliance/modulesets/{mset_id})
	DeleteNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (POST /nodes/{node_id}/compliance/modulesets/{mset_id})
	PostNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (GET /nodes/{node_id}/compliance/rulesets)
	GetNodeComplianceRulesets(ctx echo.Context, nodeId InPathNodeId) error

	// (DELETE /nodes/{node_id}/compliance/rulesets/{rset_id})
	DeleteNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (POST /nodes/{node_id}/compliance/rulesets/{rset_id})
	PostNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (GET /tags)
	GetTags(ctx echo.Context) error

	// (GET /tags/{tag_id})
	GetTag(ctx echo.Context, tagId int) error

	// (GET /tags/{tag_id}/nodes)
	GetTagNodes(ctx echo.Context, tagId int) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetNodeComplianceCandidateModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateModulesets(ctx, nodeId)
	return err
}

// GetNodeComplianceCandidateRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateRulesets(ctx, nodeId)
	return err
}

// GetNodeComplianceLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceLogs(ctx, nodeId)
	return err
}

// GetNodeComplianceModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceModulesets(ctx, nodeId)
	return err
}

// DeleteNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// PostNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// GetNodeComplianceRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceRulesets(ctx, nodeId)
	return err
}

// DeleteNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// PostNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// GetTags converts echo context to params.
func (w *ServerInterfaceWrapper) GetTags(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTags(ctx)
	return err
}

// GetTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTag(ctx, tagId)
	return err
}

// GetTagNodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetTagNodes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTagNodes(ctx, tagId)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/docs/openapi", wrapper.GetSwagger)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_modulesets", wrapper.GetNodeComplianceCandidateModulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_rulesets", wrapper.GetNodeComplianceCandidateRulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/logs", wrapper.GetNodeComplianceLogs)
	router.GET(baseURL+"/nodes/:node_id/compliance/modulesets", wrapper.GetNodeComplianceModulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.DeleteNodeComplianceModuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.PostNodeComplianceModuleset)
	router.GET(baseURL+"/nodes/:node_id/compliance/rulesets", wrapper.GetNodeComplianceRulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.DeleteNodeComplianceRuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.PostNodeComplianceRuleset)
	router.GET(baseURL+"/tags", wrapper.GetTags)
	router.GET(baseURL+"/tags/:tag_id", wrapper.GetTag)
	router.GET(baseURL+"/tags/:tag_id/nodes", wrapper.GetTagNodes)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZb2/bthP+KgR/vxctoFlOk22A96pNljZbmwaOu71IjIKmzhILiVSPpzSu4e8+kLJl",
	"2ZYdJx6cJtirxNKJ9+d5eM9JHHNpstxo0GR5Z8xzgSIDAvS/lL4QlHywQGeR+x2BlahyUkbzDj87YWbI",
	"KAGWmahIwQLxgCt3KxeU8IBrkQHv8MwCfVYRDzjC10IhRLxDWEDArUwgE25pGuXO1BIqHfPJJJg6PzcR",
	"bHauTQTNft2dh/rt3pk0bkoZH5DyxBnb3GgLvvpH7bb7I40m0OT+FXmeKilcKOEX6+IZ19b7P8KQd/j/",
	"wjmkYXnXhhdoBilkpZfFjN6IiHXhawGW+CTgR+2DfXj9pEVBiUH1HaLS7eE+3J4aHKgoAl36PNqHz3ND",
	"7NQU2uf5835APdMEqEXKLgFvANnviAY9vacPu7Vnz7t9jyYHJFUyLwISKl0l/2uWFJnQPyGISAxSYHCb",
	"p0L72JnNQaqhkowMo0RZZqQsEEFLmG6Za52XHlvXmgfL/A+4JUGFXXXbS4C96/UuWGnApImAvbjqnh7/",
	"+urwoB+wS5A+hF9eshg0oCCI2GBU+jSoYqWZLQsxNLgmOtYUnNIEMaCLjhSl0FQTmxikYLk0tsgygaOl",
	"xZlbt8XYGbHLdx8/vT+51ucfe0wmQsfAhmiyemBk1ocZMLiVkNO1dinlBebGgnVGqZEiVd9LVF5AK24F",
	"rLBKx+5RIUndAJvy71priA0pb/sbswCsoayHraOXjZBN6u3takabCshZzfrVg2bwBaRvMzeAVpVkX+Re",
	"7Qbciix3NeftVrt1cKf/2aOr/hy5QBaoaHTp+F+6Ggir5OuCkmrLuWf81bmvhCh3AQ9AIODMuvx1ajAT",
	"xDv8j797PKgt4e8ur1GKy9D43l+SiZsctL2RTJo0BUkGmcgVr5WHH7TarbYLwJm6mx1+6C8FXnJ8ImFk",
	"pA0rgzGPwbcWV1cPrVMy/hbo8puIYx/ZgtK8umdTWq7uSvv5+GdNSppaWOU+dEbz/n+X7WGth262dUYu",
	"MBKxdeTIi0GqJO+7a6GbDGw4ng4IE79CqoSWEEqhIxUJgs/VVGNrJV3M8y0Qqx6Yj0HWtxnhRxO/b1aA",
	"cGPNceX0eLbEh7nLYGEWu2pOd24SLoxLk/6OCCuCzDZAXVFaIIpRE/TvlSXXhZrKUhPdZYmM3CBHbLik",
	"k2tUbdrMYa5q093tK1Xb11f9STBe2LtXfVecGSuqfXcfYuD9aIE7kqL7/CiBz4EQqYnvoEBly5ztPfF/",
	"75Z/qpAfN6Revaw9ZdC3FIWaFAgiIROI3DS3PfrPSAmqAjwTIZinEY6nnzYmZYgpUMMbwgm4/JmY518O",
	"+mvJcOIXWsOHHekQbGk//ejTQJ8G1KrgmC2kBGuHRZqOWAQl8JvRNlgrzGNDH/Dc2IY9/ZpWMNy0nS+M",
	"pR8IP/9x542JRrtO+YsfsyYr3Hi1iRuzPlDSob3NuN/+YV4j9tBXthorcTdZ6T47UXkWoyRWgoL3ERR8",
	"sJx099qMuvcRk+5OUoJPRUjwQTLyiLg9poh0/5OQeR8pr6/RCN8f4VZZUjpm3rRBFHrl9Ufq4eXXwUer",
	"XTgmEc96bGMRT5TNUzFy5WPTr9OjNWVc3YnrzgvJGzecFZbRbHNUWJ1G7CzAW3/BPdpmLxz9GHiWCrtx",
	"fPIW7FsCCDNQmJoPU2tAPvfrPk2kdx+1pjVTlJQnZy69dTLcE3Gj9O6XFbUzpEYmIFCBmolcsZlpA/B/",
	"Vbd2AmDTCe7M+7/TJKtyiFwMVKr8kVp/UlbWzTglbQtMeYeHRh6GIld80p/8EwAA//9aFG5UBiIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
