// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Problem defines model for Problem.
type Problem struct {
	// Detail A human-readable explanation specific to this occurrence of the
	// problem.
	Detail string `json:"detail"`

	// Status The HTTP status code ([RFC7231], Section 6) generated by the
	// origin server for this occurrence of the problem.
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type.  It SHOULD
	// NOT change from occurrence to occurrence of the problem, except
	// for purposes of localization (e.g., using proactive content
	// negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title"`
}

// Version defines model for version.
type Version struct {
	Version string `json:"version"`
}

// InPathMsetId defines model for inPathMsetId.
type InPathMsetId = string

// InPathNodeId defines model for inPathNodeId.
type InPathNodeId = string

// InPathRsetId defines model for inPathRsetId.
type InPathRsetId = string

// N400 defines model for 400.
type N400 = Problem

// N401 defines model for 401.
type N401 = Problem

// N403 defines model for 403.
type N403 = Problem

// N404 defines model for 404.
type N404 = Problem

// N500 defines model for 500.
type N500 = Problem

// PostNodeComplianceModulesetJSONBody defines parameters for PostNodeComplianceModuleset.
type PostNodeComplianceModulesetJSONBody = map[string]interface{}

// PostNodeComplianceRulesetJSONBody defines parameters for PostNodeComplianceRuleset.
type PostNodeComplianceRulesetJSONBody = map[string]interface{}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Nodename *string `json:"nodename,omitempty"`
}

// PostRegisterParams defines parameters for PostRegister.
type PostRegisterParams struct {
	App *string `form:"app,omitempty" json:"app,omitempty"`
}

// PostNodeComplianceModulesetJSONRequestBody defines body for PostNodeComplianceModuleset for application/json ContentType.
type PostNodeComplianceModulesetJSONRequestBody = PostNodeComplianceModulesetJSONBody

// PostNodeComplianceRulesetJSONRequestBody defines body for PostNodeComplianceRuleset for application/json ContentType.
type PostNodeComplianceRulesetJSONRequestBody = PostNodeComplianceRulesetJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody
