// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/node)
	PostAuthNode(ctx echo.Context) error

	// (GET /nodes/{node_id}/compliance/candidate_modulesets)
	GetNodeComplianceCandidateModulesets(ctx echo.Context, nodeId InPathNodeId, params GetNodeComplianceCandidateModulesetsParams) error

	// (GET /nodes/{node_id}/compliance/candidate_rulesets)
	GetNodeComplianceCandidateRulesets(ctx echo.Context, nodeId InPathNodeId, params GetNodeComplianceCandidateRulesetsParams) error

	// (GET /nodes/{node_id}/compliance/logs)
	GetNodeComplianceLogs(ctx echo.Context, nodeId InPathNodeId) error

	// (GET /nodes/{node_id}/compliance/modulesets)
	GetNodeComplianceModulesets(ctx echo.Context, nodeId InPathNodeId, params GetNodeComplianceModulesetsParams) error

	// (DELETE /nodes/{node_id}/compliance/modulesets/{mset_id})
	DeleteNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (POST /nodes/{node_id}/compliance/modulesets/{mset_id})
	PostNodeComplianceModuleset(ctx echo.Context, nodeId InPathNodeId, msetId InPathMsetId) error

	// (GET /nodes/{node_id}/compliance/rulesets)
	GetNodeComplianceRulesets(ctx echo.Context, nodeId InPathNodeId, params GetNodeComplianceRulesetsParams) error

	// (DELETE /nodes/{node_id}/compliance/rulesets/{rset_id})
	DeleteNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (POST /nodes/{node_id}/compliance/rulesets/{rset_id})
	PostNodeComplianceRuleset(ctx echo.Context, nodeId InPathNodeId, rsetId InPathRsetId) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /tags)
	GetTags(ctx echo.Context, params GetTagsParams) error

	// (GET /tags/{tag_id})
	GetTag(ctx echo.Context, tagId int) error

	// (GET /tags/{tag_id}/nodes)
	GetTagNodes(ctx echo.Context, tagId int, params GetTagNodesParams) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAuthNode converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthNode(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthNode(ctx)
	return err
}

// GetNodeComplianceCandidateModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodeComplianceCandidateModulesetsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateModulesets(ctx, nodeId, params)
	return err
}

// GetNodeComplianceCandidateRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceCandidateRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodeComplianceCandidateRulesetsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceCandidateRulesets(ctx, nodeId, params)
	return err
}

// GetNodeComplianceLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceLogs(ctx, nodeId)
	return err
}

// GetNodeComplianceModulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceModulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodeComplianceModulesetsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceModulesets(ctx, nodeId, params)
	return err
}

// DeleteNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// PostNodeComplianceModuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceModuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "mset_id" -------------
	var msetId InPathMsetId

	err = runtime.BindStyledParameterWithOptions("simple", "mset_id", ctx.Param("mset_id"), &msetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceModuleset(ctx, nodeId, msetId)
	return err
}

// GetNodeComplianceRulesets converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeComplianceRulesets(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNodeComplianceRulesetsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeComplianceRulesets(ctx, nodeId, params)
	return err
}

// DeleteNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// PostNodeComplianceRuleset converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeComplianceRuleset(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "node_id" -------------
	var nodeId InPathNodeId

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", ctx.Param("node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter node_id: %s", err))
	}

	// ------------- Path parameter "rset_id" -------------
	var rsetId InPathRsetId

	err = runtime.BindStyledParameterWithOptions("simple", "rset_id", ctx.Param("rset_id"), &rsetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter rset_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeComplianceRuleset(ctx, nodeId, rsetId)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetTags converts echo context to params.
func (w *ServerInterfaceWrapper) GetTags(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTags(ctx, params)
	return err
}

// GetTag converts echo context to params.
func (w *ServerInterfaceWrapper) GetTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTag(ctx, tagId)
	return err
}

// GetTagNodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetTagNodes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag_id" -------------
	var tagId int

	err = runtime.BindStyledParameterWithOptions("simple", "tag_id", ctx.Param("tag_id"), &tagId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag_id: %s", err))
	}

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagNodesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTagNodes(ctx, tagId, params)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/node", wrapper.PostAuthNode)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_modulesets", wrapper.GetNodeComplianceCandidateModulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/candidate_rulesets", wrapper.GetNodeComplianceCandidateRulesets)
	router.GET(baseURL+"/nodes/:node_id/compliance/logs", wrapper.GetNodeComplianceLogs)
	router.GET(baseURL+"/nodes/:node_id/compliance/modulesets", wrapper.GetNodeComplianceModulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.DeleteNodeComplianceModuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/modulesets/:mset_id", wrapper.PostNodeComplianceModuleset)
	router.GET(baseURL+"/nodes/:node_id/compliance/rulesets", wrapper.GetNodeComplianceRulesets)
	router.DELETE(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.DeleteNodeComplianceRuleset)
	router.POST(baseURL+"/nodes/:node_id/compliance/rulesets/:rset_id", wrapper.PostNodeComplianceRuleset)
	router.GET(baseURL+"/openapi.json", wrapper.GetSwagger)
	router.GET(baseURL+"/tags", wrapper.GetTags)
	router.GET(baseURL+"/tags/:tag_id", wrapper.GetTag)
	router.GET(baseURL+"/tags/:tag_id/nodes", wrapper.GetTagNodes)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaTXPbNhP+Kxi875GV6MQ5RDfHbjJpEyeV3fbgeDIQuZSQkgCzWCZWNfrvHQD8kkV9",
	"d+Qk9Ukjcold7PNgnwXIGY90lmsFigwfzHguUGRAgO6fVO8FTd4aoNex/R+DiVDmJLXiA/76gumE0QRY",
	"puMiBQPEAy7trVzQhAdciQz4gGcG6KOMecARPhcSIeYDwgICbqIJZMIOTdPcmhpCqcZ8Pg9K55c6hvXO",
	"lY6h26+9s6/f4cZJ47op455T/q0AnL6RmaRl19c20+JOZkXGVJGNAG0ooAglGEaaIVCBqsdCloFQhinN",
	"UjtUr4rxsx29CdLd5O2QYkhEkRIfPAsDnkllffFBGFSxSkUwBmwH+y5JbBaWor36S+YuT4lEQ3WYZfJi",
	"QYJFBRqNq6LTfuDO8DZFN7d5N7lWBhyRT8PQ/kRaESgXrMjzVEbCBtv/ZGzEs5aj/yMkfMD/129WR9/f",
	"Nf33qEcpZN7L4pxfiJgN4XMBhvg84KfhyTG8/q5EQRON8m+Ivdunx3D7UuNIxjEo7/P0GD4vNbGXulDl",
	"PJ8fw+e5VkkqI4fos+Pw6LUiQCVSdgX4BZD9jKj9oisftmNXz9uqjToHJOnJTnDXsR7P2KTIhPoJQcRi",
	"lAKDuzwVykXOTA6RTGRkqwhNpGE6igpEUBGUK/aDyr2/3gfFg47a1dS5Gx/BbW2lR5/A5+8LoJE+SYsx",
	"t27Ancjy1D4X9sLeyUZn1aPL/my+ICpQ0vTK5s27Ggkjo7OCJjVU9hl3tfE1IcptwCMQCFhZ+38vNWaC",
	"+ID/8ud1VZ7cEO7u/TF8qUy0Q0aSm5jOQZkvEYt0mkJEGpnIJW+lh5/0wt4TG4A1tTcH/Gkv7IU8cELj",
	"JtK3y77v5M/mU5sO1IcwloYAmXA6yewjoKhkrIPSwuD+Wbnj77UhO91Lr6roq9kLHU93Iv4iuiLPOwQv",
	"cALtq/1sA8i1ZQfKS9X+yY6rdDHYGqz70RaFjDdH6qxKyLuCvb/Wz6IIclqo3F1Vo55g3xo11W+T7fNW",
	"2Vpva43aS4YPbhYWy83tPJgtLIib27mdoRgbO3FLLX5rR3CcNP1Z2X/Nnb9UChVBPxIqlrEg+Fg3jS7r",
	"464e4hUQqx9oukzDEl0xuoPCr4Ase89rp+fVEG8bl8FCq3vTnZzGpL/QjdpEbLRvtXLb25fdlM3rQZSW",
	"BJlpkbUpweUFgSimXXx8Iw3Zmt+V95bS39fl2DbixJJKnEvKrdA143UNGl3bk3R1Bd2Febgb7/BA1g0f",
	"Obcz5/BHYFyqxxs4Vtsya7sjwd7Y4Q/j1MNBft4x9Xo3/z2DvqWstcRMEIloArFtvrdH/1HLtq8rdYZ/",
	"EClrptGflYdrcx9iCgTLwV6AnT8TzfxZgjpbzbYLN9AKwh2Bb61jxw76dKBWB8dMEUVgTFKk6ZTF4IFf",
	"j7bGVmIeGvpgxU7ujJYwXFcv7D7uG8Jvv11kx+Zp8Th1eef3ZB03qjrg6RBus38KWwd5m2xPdt3DHWVf",
	"tkNd2aoxxsN067Eb3lm1fohmGGvFwl0UC/fWq+FRq91wF7UaHqRV+L0oFe6lUw+I20Oq1PBRo5o6Up56",
	"96pkl2K0JC1XX8V47M7cD6rVGw9p3/36zaS4SllejFIZlfnyF1eIttMTuJOGpBozZ9qh0tdir9OE71Rj",
	"PaAPwm17vT8jMa40sBO0C2nyVEwtXKx8PzFdAdsyaqs+WSBn3PG5go9mm68Vmnfst8dadKfbLKTTbwNP",
	"3wGt7Z+dBfs6AYQKFCabbnoFyJdu3IdB+j/Qa5egSJr49982f6v6sGsx7uy9jku71hvzTqr5j4GYyCWr",
	"TDuY9Ud96yAA1n3nUHn/d6pwnQ6Ri5FMpXtrezv3mbVNrl8XBaZ8wHt9Pr+d/xMAAP//7lku+OQmAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
