// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package feeder

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /checks)
	PostChecks(ctx echo.Context) error

	// (POST /daemon/ping)
	PostDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostDaemonStatus(ctx echo.Context) error

	// (POST /instance/action)
	PostInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostInstanceStatus(ctx echo.Context, params PostInstanceStatusParams) error

	// (GET /node/actionq)
	GetNodeActionQueued(ctx echo.Context) error

	// (POST /node/actionq/done)
	PostNodeActionQueuedDone(ctx echo.Context) error

	// (POST /node/actionq/running)
	PostNodeActionQueuedRunning(ctx echo.Context) error

	// (POST /node/disk)
	PostNodeDisk(ctx echo.Context) error

	// (POST /node/sysreport)
	PostNodeSysReport(ctx echo.Context) error

	// (POST /node/system)
	PostSystem(ctx echo.Context) error

	// (POST /object/config)
	PostObjectConfig(ctx echo.Context) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (POST /sanswitch)
	PostSANSwitch(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostChecks converts echo context to params.
func (w *ServerInterfaceWrapper) PostChecks(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostChecks(ctx)
	return err
}

// PostDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonPing(ctx)
	return err
}

// PostDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonStatus(ctx)
	return err
}

// PostInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceAction(ctx)
	return err
}

// PutInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutInstanceActionEnd(ctx)
	return err
}

// PostInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceResourceInfo(ctx)
	return err
}

// PostInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sync", ctx.QueryParams(), &params.Sync, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceStatus(ctx, params)
	return err
}

// GetNodeActionQueued converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeActionQueued(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeActionQueued(ctx)
	return err
}

// PostNodeActionQueuedDone converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedDone(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedDone(ctx)
	return err
}

// PostNodeActionQueuedRunning converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedRunning(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedRunning(ctx)
	return err
}

// PostNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeDisk(ctx)
	return err
}

// PostNodeSysReport converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeSysReport(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeSysReport(ctx)
	return err
}

// PostSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostSystem(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSystem(ctx)
	return err
}

// PostObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostObjectConfig(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// PostSANSwitch converts echo context to params.
func (w *ServerInterfaceWrapper) PostSANSwitch(ctx echo.Context) error {
	var err error

	ctx.Set(string(BasicAuthScopes), []string{})

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSANSwitch(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/checks", wrapper.PostChecks, options.OperationMiddlewares["PostChecks"]...)
	router.POST(options.BaseURL+"/daemon/ping", wrapper.PostDaemonPing, options.OperationMiddlewares["PostDaemonPing"]...)
	router.POST(options.BaseURL+"/daemon/status", wrapper.PostDaemonStatus, options.OperationMiddlewares["PostDaemonStatus"]...)
	router.POST(options.BaseURL+"/instance/action", wrapper.PostInstanceAction, options.OperationMiddlewares["PostInstanceAction"]...)
	router.PUT(options.BaseURL+"/instance/action", wrapper.PutInstanceActionEnd, options.OperationMiddlewares["PutInstanceActionEnd"]...)
	router.POST(options.BaseURL+"/instance/resource_info", wrapper.PostInstanceResourceInfo, options.OperationMiddlewares["PostInstanceResourceInfo"]...)
	router.POST(options.BaseURL+"/instance/status", wrapper.PostInstanceStatus, options.OperationMiddlewares["PostInstanceStatus"]...)
	router.GET(options.BaseURL+"/node/actionq", wrapper.GetNodeActionQueued, options.OperationMiddlewares["GetNodeActionQueued"]...)
	router.POST(options.BaseURL+"/node/actionq/done", wrapper.PostNodeActionQueuedDone, options.OperationMiddlewares["PostNodeActionQueuedDone"]...)
	router.POST(options.BaseURL+"/node/actionq/running", wrapper.PostNodeActionQueuedRunning, options.OperationMiddlewares["PostNodeActionQueuedRunning"]...)
	router.POST(options.BaseURL+"/node/disk", wrapper.PostNodeDisk, options.OperationMiddlewares["PostNodeDisk"]...)
	router.POST(options.BaseURL+"/node/sysreport", wrapper.PostNodeSysReport, options.OperationMiddlewares["PostNodeSysReport"]...)
	router.POST(options.BaseURL+"/node/system", wrapper.PostSystem, options.OperationMiddlewares["PostSystem"]...)
	router.POST(options.BaseURL+"/object/config", wrapper.PostObjectConfig, options.OperationMiddlewares["PostObjectConfig"]...)
	router.GET(options.BaseURL+"/openapi.json", wrapper.GetSwagger, options.OperationMiddlewares["GetSwagger"]...)
	router.POST(options.BaseURL+"/sanswitch", wrapper.PostSANSwitch, options.OperationMiddlewares["PostSANSwitch"]...)
	router.GET(options.BaseURL+"/version", wrapper.GetVersion, options.OperationMiddlewares["GetVersion"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Btdcxu38a9grn1IZy6ibCUP4Ztixx23Hccxk/bB8mhAYMlDfAecARxlJsP/3ll83AcPR1Ky6KRNnmwe",
	"gP3exe5i9WvGVFUrCdKabP5rVlNNK7Cg3S8hf2hAbxdbyfzPbJ59wC9ZnklaQTbPDK7lmWEFVBQ32W2N",
	"35dKlUBlttvt8kyDqZU04IB+dXmJ/zAlLUiL/6V1XQpGrVBy9rNREr91AP+qYZXNs7/MOkpnftXMXmu1",
	"LKHyWDgYpkWNYLJ59i3l5A18aMDYbJdnX10++RxYf5K0sYXS4hfgHu3V50D7Quml4Bykx/nN58D5TMlV",
	"KZiT7tefR6cvpQUtaUkWoDegyXdaK434n1OolHwt5PqaMagt8HuRU2tVg7bCG6hUHG7vhC1uKcMDtx8a",
	"aDzEITmlMJaoFWFlYyxoggcNwZOkBsmFXBN/lHhAJsszYaEyY1B9EM6z8uhIxmoh18hk+EC1plv8rZY/",
	"A7OOUtXYW6bkSqynqfTbCUI3xBbUEg0fGqHBkNffL34kM1qLmd80C7Amye3BOk5p98EfS2mWOwUSY6lt",
	"DLGiAmNpVaM0y5IsgWhYaTAFcLJSXkyd3hfu1J+a/z/Q/CF17+I148i6Zh7APoE/FkCWsBaSKE1ARg04",
	"lsHYG5nle1qnLaQRO1SvN2MUtgDCVFVRyUkpJBCq103lrtCe3I5q0VE5hu6JD1S3nkCEJG9ePLu6uvrm",
	"FZUKxVJRm1IB0wNm2os4z0AmTLknogcgQ/Z9qhDZPhTavc7+JSSk5NF6wBEob6BW2gJ/FfejR2gRhDki",
	"saa2SC+IhDiCKHAtwa4W3KTtobUyo8oNcOJ2JiAYMAYjS9N47OMNzhEmCQvL+dTB21IlIoH/tQSyb7op",
	"QJG0JH5c9DGkoBv0NJCEGiPWEjjhDcIgPXl4G08g2YA2Sf/Fw6oGaTaMsFKAtIRTS0k8MILl8ksXzng2",
	"f+vVnUenDi7slR3011pLR0XwmsD7npaip3oHajU0kHj0hHejiJdnPasf3Tj3igEpOSaNuKcAF59qwYlY",
	"kQqoFHK9asoJ2z5ikEdMbrzcLA3YxNKeyqJ4tZe9PxVVNhByoGVayiHj7+cCQ4FP+N0eRW5XCstzYd6P",
	"gfI0/xMCrRSHMrkS7vXJiKVhPXVTGfGLM68QqueZkPbqaadnIS2swSXLjYE+Yb2VDUiu9HHxOMX0iQ34",
	"A+wWUOQ1RwmlxPlSGkslgzdgVKMZvJQrNRavCF/bO2a4/B625vByUmIbWjYosn3mcH9cTdG8f23pUwzK",
	"m7aj9BSYn3IVTlqPVbUq1Xp7nNqgUyf3Q2pbtKFhzx+o7fcCuoOTtJ37OnAUdWhSTKEM0b0P8HNSkuNC",
	"xAmpcJ597/73rM3e99LSuk6KCq/vUNuM1riub12yfGhx6CxH01SQm+S+VQkfbyv6MR1K/OogJdtftVSv",
	"B9dDb0OlpLBKA7/VITTcMtXIid1KswKM1dTC/VJATe961VMbO5dbm8yMDFM13E9693S6lGG+VsY+K4Cl",
	"LHNDy6E6439SpOz93lB9L1PYo9cdzz0FU2R3fZl0sW1OK61Pq57J/crnE3D3C+dHKonPGOq8QDv2Doe7",
	"Tj1TUZwVVK73okWSc6WJCDfCKQKYvh00bIRqzG1Tc2qB31I7cEv8+CVmw8mq5QFnzqaKcN1ECR7RRGh4",
	"jhRg4aMd03ZNiqai8ksNlNNlCQQ+1iWV1JeHNTCxEoxYRWwhDFGMNVqDZICGbQu4kbXHd3FznA9HQYrm",
	"H1x3q+vB7FmOrzDTtxD4zti9FCUmEtZ+njQ69AA8h2qdDbudqpA2bIKIVN7ckTUURouiA9hjMG+FerAK",
	"6uvlufIV52RtGFqUGkxTWlJrxcAY4GS5dSU84k60yx5VgXoqATCWg9YTVSdXjT1R2kMJa1dYBgAtkmOC",
	"fNNImbzCkt2geIkMGsDENx4m4igdbU4WbgevY0RwjJFEkKfdwknZ7cDxj9EUgafoGpUuyU6uu9fRGF34",
	"FYbQpWpsTu4KkO57aOviksEwjdKzhiyhoOXqRi63hEpli5giqJVbDhd8TqhxUFR1RZgqS2BWaQyi9D1o",
	"whWYixv5HFa0Ka3xMRUIbWwB0gqG940De0GuA/jGhjDb5RAh6o5PIc0aVlgyJ2Nxni2uXy3uhGXFdElC",
	"ORcoL1q+Ht4d47i7HwU0vUOCa08zUFYQ47DFDmGOkSB2C1FHF+SF0oTeyKVWjHKYhwOmUHc5kQb/Jbj5",
	"FyUBfwz46nSf1reLObTy+qZr1KZGqsDrKNB2J1xBN5FlpGByLTatIgIYtCCBDNOtIUh1tC+8VV2nr6lc",
	"a8oz2rPgqeSrl/2FFCdl9Yut8Yaf0CiUYGGim2c1Ze+Bk5UowZCwFY09BmpiBN7xaNwlNSg5xIIGfiNt",
	"AUITrC9M/4jTzemVDKJOhS5LW9l66tAAotV4+zLEZ0I8UIl7kcobGcl01ldBtURHpRVwctNcXl6xeP+5",
	"XzBDBDO/guz4r0TpG5nczioedncf0Vc9VqTaSRJjFFGy3JKCGiKVBG+3XT0oJHVDD+MiuCnLiTtWs0Js",
	"gBSq5IbABvTWySchnig+pH7uowX6T2jWx6jkAa2U7nSOIPq4MGARqeyNpBpDY6U2wPsu2E1l5KnmDHtP",
	"14kmNYJPNzgx6y/Le+YCkwmbEesDlni4a3SSd3bpu2OpdVdEnPJWszU2lZj3JHXSpRn3n9QV6jG1V+t3",
	"C/CRVjW6Y3Z5cXnx5GgeP11+uCcp1mhhtwukNjxLUCPYdeO7Jo4LZz34tcNVWFv7d0yqQcfd/teLaAn/",
	"+M+PcTzIgXCr+zB2u7xt8lphHWOx/FoBcNCE1qKnwHl2dXF58bUr5muQuOg/XWa+2+O4mLGua6JMopR6",
	"3ZiC+E3OS1Daro56yXG167t4aYKx3yq+fbxJlw7BbqgxqxvYn5t66mdshhx8/8+BCrP524Hy3r7b5b8O",
	"FPT23Q6NgK4N2kUQ0DuEMfMv8bM6prpJkb3xD/NtejM1uDEhz15D6Hwy7SE5Sa5Pp4C2+2aJAaNdnj29",
	"/GosoUoYI+R6TzJxjCEPIxdB2GHVJR6ByE/Rp8uahursStoHKPSgFhfxHfS8egxoHleTeyNDbmru8vhh",
	"3NQNEx7b+6Q3AXhs71VvjO7wXtz0WDYS23azbgYmbSXf+gfp9k0azZmStdiAjF1Sl5Cl7SW+F13HR/lz",
	"WEysSU+2k0fEuv/snJhz6g9EEPpHNrw8q5uEiX0n+cMMrNmzr+9ck+x3YWJJE/ATV39GHh952ve9mACm",
	"A9BPrr1PlCZMA/4vAiARAEEARwLQYM7gPDaSRPVQi0kziak1GtJoWPL3Yk1hAv3Y3m9+W8s7lhktrNLd",
	"M9DTiyedzYW0jVNLL46YXJsl9f+04m2a4W7LrP+nF8jJOU31PhnW5QEjDVIx7uGemIYxMGbVlOWWfGG2",
	"khVaSdWYv/nU+elxSN0UcIyX5Au6D+kPGT6xlAhJ2wfEHAYphuJcg+3NYpr4yBBbSOOOdMKU/w72leLh",
	"ZvXN/yxtFI9iksPXikQahQXvbyzvGQ8Pa+mwYcDuS1wDA7FJvKyNw8a+sN0j3nncf/RW+PC8pktmflvN",
	"6N5LXVI5XeuUvZfqrgS+BuP1U1vXT3WXqm58m3ylylLdYTXfPeORUhh7caL64tPh+TUYMf3vKpHH2drT",
	"EkCnRjxjiB/harwuDmjGjeadRxXd9OBDFTDFTyrNe0yxm63R3ZNUuk+qjA2vTHHzASl3b1yHRF01pRU1",
	"1XaGCe2X8T3zNGl3KB4q7ZaRP0uxaAXxqWPaBPwmNFKmNqC3E0aw8LDO42iB0E/Qu2OBWnrkbwv/kLYw",
	"/CvA04NxaNGcEogHU8/nsZEBik+uvT9XNA4vWReR15DTj/LxxR1dr90j2iel4Uf/MtOn2r8L047iqptl",
	"KViQl6HSdNMxh+zUP6T3tahWhJLF9at2HCQMAvmxEyE3IK3SAjgRdu4mKHrjMmY4SxJf800cKsGlO6Xf",
	"gyY11QYMEdIqD8UfAZP7GRmXctJSUNxl6bIE0w4TdVQYPxQQz/oRpgE/HFhJNYINAx6oZ96UEEd7phLW",
	"bsToPK7YwX+oHw4EfcQT7xO1H8lre6/yySJcg220JLQWvenhkU//u106W2kdsT9OUd2+INOaLkUp3JDC",
	"u52Xqt7ELlejy2yeXcyy3bvdfwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
