// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package feeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /checks)
	PostChecks(ctx echo.Context) error

	// (POST /daemon/ping)
	PostDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostDaemonStatus(ctx echo.Context) error

	// (POST /instance/action)
	PostInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostInstanceStatus(ctx echo.Context, params PostInstanceStatusParams) error

	// (GET /node/actionq)
	GetNodeActionQueued(ctx echo.Context) error

	// (POST /node/actionq/done)
	PostNodeActionQueuedDone(ctx echo.Context) error

	// (POST /node/actionq/running)
	PostNodeActionQueuedRunning(ctx echo.Context) error

	// (POST /node/disk)
	PostNodeDisk(ctx echo.Context) error

	// (POST /node/sysreport)
	PostNodeSysReport(ctx echo.Context) error

	// (POST /node/system)
	PostSystem(ctx echo.Context) error

	// (POST /object/config)
	PostObjectConfig(ctx echo.Context) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostChecks converts echo context to params.
func (w *ServerInterfaceWrapper) PostChecks(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostChecks(ctx)
	return err
}

// PostDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonPing(ctx)
	return err
}

// PostDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonStatus(ctx)
	return err
}

// PostInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceAction(ctx)
	return err
}

// PutInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutInstanceActionEnd(ctx)
	return err
}

// PostInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceResourceInfo(ctx)
	return err
}

// PostInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceStatus(ctx, params)
	return err
}

// GetNodeActionQueued converts echo context to params.
func (w *ServerInterfaceWrapper) GetNodeActionQueued(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNodeActionQueued(ctx)
	return err
}

// PostNodeActionQueuedDone converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedDone(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedDone(ctx)
	return err
}

// PostNodeActionQueuedRunning converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeActionQueuedRunning(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeActionQueuedRunning(ctx)
	return err
}

// PostNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeDisk(ctx)
	return err
}

// PostNodeSysReport converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeSysReport(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeSysReport(ctx)
	return err
}

// PostSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSystem(ctx)
	return err
}

// PostObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostObjectConfig(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/checks", wrapper.PostChecks)
	router.POST(baseURL+"/daemon/ping", wrapper.PostDaemonPing)
	router.POST(baseURL+"/daemon/status", wrapper.PostDaemonStatus)
	router.POST(baseURL+"/instance/action", wrapper.PostInstanceAction)
	router.PUT(baseURL+"/instance/action", wrapper.PutInstanceActionEnd)
	router.POST(baseURL+"/instance/resource_info", wrapper.PostInstanceResourceInfo)
	router.POST(baseURL+"/instance/status", wrapper.PostInstanceStatus)
	router.GET(baseURL+"/node/actionq", wrapper.GetNodeActionQueued)
	router.POST(baseURL+"/node/actionq/done", wrapper.PostNodeActionQueuedDone)
	router.POST(baseURL+"/node/actionq/running", wrapper.PostNodeActionQueuedRunning)
	router.POST(baseURL+"/node/disk", wrapper.PostNodeDisk)
	router.POST(baseURL+"/node/sysreport", wrapper.PostNodeSysReport)
	router.POST(baseURL+"/node/system", wrapper.PostSystem)
	router.POST(baseURL+"/object/config", wrapper.PostObjectConfig)
	router.GET(baseURL+"/openapi.json", wrapper.GetSwagger)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbSZMbtxX+K6hODk4VRVIzyiG8aU0pqZLkoZ0c5CkWCDw2YTWBFoDmDK3if09h643o",
	"ZRbKjqWThg3gLd97jbe1viRE7HLBgWuVLL4kOZZ4Bxqk/cX4jwXIw/LAifuZLJLP5kkySTjeQbJIlFmb",
	"JIpsYYfNJn3IzfO1EBlgnhyPx0kiQeWCK7BEn83n5h8iuAauzZ84zzNGsGaCz35VgptnFcG/Stgki+Qv",
	"s0rSmVtVsw9SrDPYOS4UFJEsN2SSRfICU3QFnwtQOjlOkmfzp1+D688cF3orJPsNqGN7+TXYvhFyzSgF",
	"bnj+/esA/JZrkBxnaAlyDxK9llJIw/8Vhp3gHxhPnxMCuQZ6J3FyKXKQmjlv4YLC6obp7QoTc2D1uYDC",
	"UWyKkzGlkdggkhVKg0TmoELmJMqBU8ZT5I4iR0glk4Rp2KlTUnUS1s0nwauVloynRkn/AEuJD+a3WP8K",
	"RFtJRaFXRPANS7uldNuRoa6Q3mKNJHwumASFPrxf/oRmOGczt2nmaXWKW6M1LGn1wB2LWZZaAyKlsS4U",
	"0mwHSuNdbtDMMrQGJGEjQW2Boo1wMFV2X9pT3y3/J7B8n7mP4c63Yj0njkDbhrh8fiIcluneBpWg2iDQ",
	"a0gZPwXBPvamrZwVMY6u3ry8vLz8xzvMhZF8h3UMJSIbEpaBa5IAj3gbcPoAZjnW26iyCpQyTl4UjMY3",
	"WJv0LK0ykUaXO0nuQSpvnqaOegtI5MDVniCSMeAaUawxCgdOFLMx3noxTRYfnZaTYP2KUbChB72ltfcJ",
	"L7CDv6FcCcL1iStPvAv6iF+/fpoe2QFGSwG7K8blFVOfTonSOPAdsO8EhSy64q+STieRkHa9Tor9BmbB",
	"u94iYVxfXlSWYlxDCjY+FwrqgtVW9sCpkMPwWPPUhfX8Pe2SUNB1YhCKwfmWK405gStQopAE3vKNOIWX",
	"+aflVdFc/gQH1b8c936cFTCsqzkeNsdUaN9Scox/SYugFXwMzU6H0CIXmUgPwxy9mSyUfZZYltdMy8Wx",
	"rqf31cFO2c59u1iJKjYxpd4JCuaN7dGndJq+LNi+9SMC6iR5b/96WeYArXCY51GoiNjtfIZ0skZlvrIh",
	"t29R3S2SAt9H920yuF3t8G38dnCrjPesaixT0PENO8GZFhLoSvq3fUVEwTt2C0m2oLTEOq559x2Jb2o5",
	"WHkdrg86miMpInK4G3p3fOlijvlBKP1yCyTmmXucNc0Z/oiJ0vq9x/JOrtCS1x6fOAm6xK6qu3jKrsYl",
	"6ONycHS3JHwE73r6/UiJ9RmvOgdopV7/dVeZp+sWJ1vM09ZtEdVcSMR8RBgDQHd0kLBnolCrIqdYA11h",
	"3XgtzcMnJo+OcbnPmbOZwoebgOCAJXzb5MQAGm71qWzP0bbYYf5EAqZ4nQGC2zzD3NbJSOVA2IYRpAXS",
	"W6aQIKSQEjgB49h6C7/w3PGb/jKsh5UgJvOPtkbuquRMiMI8ntBScPX1nQzFOnLQzlh3Dx59NdOerLoq",
	"rT1xzc1RaXAlVhOIkkVF0Cs3KcHsLWjq9nglOMRd2peivsEhQRWZRrkUBJQCitYH4yD2LrW+0UqCHtNw",
	"sivwK01Byo7KlYpCj0S6ia5hVxIomQwBeVVwHg1djPYEj0b7CJmtnZEDn2yO1mC9YdgwGFJEdTVb1Ois",
	"tvHCD8kUiMfkWh7UFeRC6kiaDRn4Onx8grVhWbOWXTOO7dBh4Ir2zDyFmKg5Jp9wChHwJInnkzYMZtkd",
	"X5KOC8TUyWkPBv1l1ECu4K6YKp5ZlTxlxziGiDooHYtUNaRGeVPYP6pMqinVSn6rBbjFu9w4QjKfzqdP",
	"B63fHY9te40UkunD0kjrWK2xYuR54coIq4Vt/5mnFa+t1rnrPWIJMux2v94ET/jXf38KIzBLwq62aRyP",
	"k7KRoZm2ioV8ZANAQSKcs5oBF8nldD69sNltDtwsukfzxJU/VosZqcoIoSK5xYdCbZHbZCOAQdsmFm+p",
	"Wa0KEYcmKP1C0MPjDZAqBsemxbQsoD0bvHCjq6YG7//dMGGy+Ngw3sfr4+RLw0Afr4/GCXCqjF94gK4N",
	"jZlrcM/yEAOikF25fndZM3TNQzrwrFVI58O0xmQUrhddRMt9s8jc7jhJLubPThHaMaUYT1vIhOnAxE8y",
	"PNh+lSlUCvkQe+LUANgwZ5Xn3cOgvVb0hdS57ejZPK4lW5M4O42eDx82m6qB+dDep7Up99Dey9p0un+v",
	"2fRYPhLq2Fk1jIp7yQs3SCpnScadMUrZHnhoG5hrt8NfQgP1eRh6nMNjQrI22k8ekWt7tBIZH3rgwkTu",
	"G3a8SZIXERd7zen9HKxo+ddrWz3+IVws6gJuSvr95nE3T9nwDglg/AL62fa7kJCISDB/BQIoEECGwMAF",
	"1JilncdHoqzu6zFxJU1qbRzp5BuEx7fOUPaw1EJWvcOL6dPKLj61oVjj6YBZykyi/ondxzjO1ZZZ/RM8",
	"o8k5zXmXLGTeY0iPirLTHqQKQkCpTZFlB/SDOnCylYKLQv3NpZcXw5SqD1DCnYJ+wG1K3+QVY9Jtn9h8",
	"Npz99K0JZwoaVb1CFTpUJvzYx4XeAtfGd4BWrcKmK/8T9DtBffRxnaMk7hSP4pLNVlck1TBF4e+M94z6",
	"rmz82lCg24hLIMD2kbbs6bXRBtt2gM/z+p80mu8f+6uA//taRtbavFHjBPQRJp+4uMmApqCcfXKNMKcu",
	"8MiCW0NtRJaJG1PxVj1glDGlpyPNF/rO57dg4PT/a0QavrEalyRZM5ozCrm5f+Fs0WMZ+z3HeUxRfXJy",
	"XwN06XPGVMjCrg5KVl38eC9RKO3wLjf3oFyNBfqg3hWZZjmWemaSvidhkjwO7YrFfdEuFflergQvCOOA",
	"bhdwm4yTErEHeehwgqWjdZ4XzQv6ALtbFbDGA5+1f5O+0PwAffxl7NsYYy7ixqdy5/GRBosH16df6zb2",
	"055p0NXn9Cf5+PIGp6kdND0oDR/8TwEu1f5DuHaAKy/WGSMer9rMMFr+SNCF5AjnrPaxzwma/ymXzlbU",
	"BO6PU86U8y2c4zXLmB2hXh+dF8p96C8UMksWyXSWHK+P/wsAAP//SBl8lu43AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
