// Package feeder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package feeder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /daemon/ping)
	PostDaemonPing(ctx echo.Context) error

	// (POST /daemon/status)
	PostDaemonStatus(ctx echo.Context) error

	// (POST /instance/action)
	PostInstanceAction(ctx echo.Context) error

	// (PUT /instance/action)
	PutInstanceActionEnd(ctx echo.Context) error

	// (POST /instance/resource_info)
	PostInstanceResourceInfo(ctx echo.Context) error

	// (POST /instance/status)
	PostInstanceStatus(ctx echo.Context, params PostInstanceStatusParams) error

	// (POST /node/disk)
	PostNodeDisk(ctx echo.Context) error

	// (POST /node/system)
	PostSystem(ctx echo.Context) error

	// (POST /object/config)
	PostObjectConfig(ctx echo.Context) error

	// (GET /openapi.json)
	GetSwagger(ctx echo.Context) error

	// (GET /version)
	GetVersion(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostDaemonPing converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonPing(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonPing(ctx)
	return err
}

// PostDaemonStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostDaemonStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostDaemonStatus(ctx)
	return err
}

// PostInstanceAction converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceAction(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceAction(ctx)
	return err
}

// PutInstanceActionEnd converts echo context to params.
func (w *ServerInterfaceWrapper) PutInstanceActionEnd(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutInstanceActionEnd(ctx)
	return err
}

// PostInstanceResourceInfo converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceResourceInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceResourceInfo(ctx)
	return err
}

// PostInstanceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PostInstanceStatus(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInstanceStatusParams
	// ------------- Optional query parameter "sync" -------------

	err = runtime.BindQueryParameter("form", true, false, "sync", ctx.QueryParams(), &params.Sync)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sync: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInstanceStatus(ctx, params)
	return err
}

// PostNodeDisk converts echo context to params.
func (w *ServerInterfaceWrapper) PostNodeDisk(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostNodeDisk(ctx)
	return err
}

// PostSystem converts echo context to params.
func (w *ServerInterfaceWrapper) PostSystem(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSystem(ctx)
	return err
}

// PostObjectConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PostObjectConfig(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostObjectConfig(ctx)
	return err
}

// GetSwagger converts echo context to params.
func (w *ServerInterfaceWrapper) GetSwagger(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSwagger(ctx)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/daemon/ping", wrapper.PostDaemonPing)
	router.POST(baseURL+"/daemon/status", wrapper.PostDaemonStatus)
	router.POST(baseURL+"/instance/action", wrapper.PostInstanceAction)
	router.PUT(baseURL+"/instance/action", wrapper.PutInstanceActionEnd)
	router.POST(baseURL+"/instance/resource_info", wrapper.PostInstanceResourceInfo)
	router.POST(baseURL+"/instance/status", wrapper.PostInstanceStatus)
	router.POST(baseURL+"/node/disk", wrapper.PostNodeDisk)
	router.POST(baseURL+"/node/system", wrapper.PostSystem)
	router.POST(baseURL+"/object/config", wrapper.PostObjectConfig)
	router.GET(baseURL+"/openapi.json", wrapper.GetSwagger)
	router.GET(baseURL+"/version", wrapper.GetVersion)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW3PbuvH/Khj8/w/JDI8k22k7VZ+cW4/bTuxaTvtgezQQuKJwQgIMACpWMvruHdx4",
	"kUBJdqzMmcl5skWAe/ntD4vFgt8wFUUpOHCt8PgbLokkBWiQ9hfj/65AriYrTt1PPMafzROcYE4KwGOs",
	"zFiCFV1AQcwkvSrN85kQORCO1+t1giWoUnAFVuir0cj8oYJr4Nr8S8oyZ5RoJvjwNyW4edYI/H8JczzG",
	"/zdsLB26UTW8kmKWQ+G0pKCoZKURg8f4NUnRNXyuQGm8TvCr0cmP0PqRk0ovhGRfIXVqz36E2vdCzlia",
	"Ajc6//RjAL7gGiQnOZqAXIJE76QU0uh/S6AQ/Irx7JxSKDWkjzKnlKIEqZlji5j9BlRPvzC9EJWeUsHn",
	"LDMDXWNypjQSc+SmI0NOhfSCaCThc8UkKHR1OblBQ1KyoZs09LISzDQUaltmSxZOAq+Vloxnxk3/gEhJ",
	"VnjdPHCvxRBLLTBIaaIrhTQrQGlSlAp9YXmOZoAkzCWoBaRoLiTiIoUGz4l96w9EdyC6C8Z1yFHWrHPq",
	"BGxiQ+rnW8YRmS1tEgyu7TE/wTPIGN8GwT5GTlNDAsQ4un7/5uzs7K8fCBfG8oLoGEpUdiysE22Cgafb",
	"6oCn36GsJHoRdVaBUkzwaVWxND7BxmTH0DQXWXS4V+QSpPLh6fqoF4BECVwtKaI5A65RSjRB4YUtx+ye",
	"ZFmc4vGt8zIJ0W8UhRh60De89pzwBjv4g5BcZHOWG5Z7HO632Jx4FvpNqr2yu6TswWPDBzsrpuUtU5+2",
	"haZx7HuQL0QKeXTEZ5NenkjI+laUYl/BDHj2jTHj+uy0CRbjGjKwW0qloG1Ya2QJPBVyPzw2Qm1jvX4v",
	"uxYUfE0MQjE4L7jShFO4BiUqSeGCz8U2vMw/rbNFd/gTrNTu4fgCIHkF+301r4fJMRc2E5U8hF/SImgN",
	"P0RmLyG0KEUustV+jT5MFspdkZjUmWaD4kS3K9LmxV7bjp1grEWNmphTH0QKZsXu8Kcmza7Cza76A/bU",
	"BF/a/97UZcDGjliWUaioKApffGyNpbKc2l1316B63GYKfBmdN8/hYVqQh3h2cKOM7xjVRGag4xMKwZkW",
	"EtKp9Kt9SkXFe2YLSRegtCQ67nl/jiRfWmVYnQ5nKx0tkxQVJTwOvUcuuhgxr4TSTWW/TZQ6pvEykuaV",
	"0uCrsd4CsT3rwDIxZPUDdLdL2WcqUo+YMxygjXu780YTnr50SBeEZxvLLuq5kIj51HoIAP1pVsKSiUpN",
	"qzIlGtIp0R1+m4e/mJo0puUp7xwtFD5vBwT3RMIfmbfzN2jC8m3rztGiKgj/RQJJySwHBA9lTrg9zSFV",
	"AmVzRpEWSC+YQoLSSkrgFAy19QLueOk0Du54NF3UfOiqvVkA+vXm5iqcnqhZcy9ur9+/+cvp2cl9gibg",
	"jg1/foky4GDyWopmK6dTSGaOMcqd/c05K24dihnXSpqa6RximKiFkDrZhEZVRUHkakM4MnIHCF1oNPn1",
	"8uO/3t7xD5c3yMULzaUo2oZp0W9mguDB1OF33LhUVrIUCpSZlAtKcvbVReUFDLJBgirFeGZeNUX/EpA/",
	"kd9xDpnQzM79G1IAKALr2eDVy2jINsnnaFMHMmAW415J6CeSQWQblzS+99iVnuePXGmu+Ret6bMdG9Lu",
	"kmtPOnT5uFmy1iUv2SmOIaJWSscWYwupg+qpMP+gkqrlVFdrawAeSFEa6uPRYDQ42UuD/pRjT+O0kkyv",
	"JsZap2pGFKPnlSs5rBe2W2CeNroWWpeuVUEkyDDb/XofmPCP/96EDq8VYUc3ZazXSX3o8Wsah5Q7B0hB",
	"IlKyVgDH+GwwGozsBl4CN4PhkSuVrBdD1+EZlqHmEEpvZ4tr1/CpN/q+RptdbSYedmVepHi8WdY4zEHp",
	"1yJdPV8Xtatk3Y2tlhVsNslPR6d9Qut5w0ijdZ3g09GrbYQKpmyu6iIT2mOJb+V5sP0oU6g2sk0yPL7t",
	"0Ov2fp1861Do9n5taEoyZZhLMgPgvRHR1fDEgO6M4iQkyePG0at53khutHjt9cFo/8tmUnPDsW/uSeta",
	"Yt/cs9Z1wu65ZtJzcSQUn8OmGxtnyWvXSa2bqYbOBGVsCTzU+iaR9PAltA/OQ9fvGIzxwg/nyTNq3Wws",
	"RvrnHrjQkv6JiZfgsopQ7B1Pn0awaoNf72xz+HdBsSgF3DXBH5nHZZ663RNKmngC+mgPqebATCWY/4IA",
	"FAQgI2BPAup0ko/DkaiqpzIm7qQpFg2Rti7hnj86+6qHiRayOfCfDk6auPjSxhzoB3vCUlcS7W8ibuM4",
	"N1OG7W8mjCfHDOdjqpDRjkB6VJTtdSJVUQpKzas8X6EXasXpQgouKvXSlZen+yU1N7Ahp6AXZFPST5li",
	"TLk9TMOV3GFZxXZDzTsKuTZx5SjbQ+BwhXCkXNLcUDw1gfT5c8TcYWFv9QKiwBvwkJtkzKNiCXLVA/LE",
	"yToOxN7Qp+IbXCCa7Pm05Kdcgt2PVQ5fhr7iO2QJdu7UjsORjorv3sp/1Dr0rZ5B8NVfvXUR/DvoyReS",
	"ZbbLFNvGDgZw7wdEl//83VA7wFVWs5xRj1erYeih6tovQVeSI1Ky1mXGFpr/qYe+C81ddAzaezF+EhaU",
	"lGTGcmb7p/drx0K5DKVYJXM8xoMhXt+v/xcAAP//iBV5NsoqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
